runtime: python311

# Instance class for App Engine
instance_class: F2

# Environment variables
env_variables:
  DJANGO_SETTINGS_MODULE: "photography_config.settings"
  PYTHONUNBUFFERED: "True"

# Handlers for static files
handlers:
  # Static files
  - url: /static
    static_dir: staticfiles/
    secure: always

  # Media files (if not using Cloudinary)
  - url: /media
    static_dir: media/
    secure: always

  # All other URLs
  - url: /.*
    script: auto
    secure: always

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

# Health checks
liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
