[phases.build]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.deploy]
cmd = "bash start_railway.sh"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
DISABLE_COLLECTSTATIC = "0"