[phases.build]
cmds = [
  "pip install -r requirements.txt"
]

[phases.deploy]
cmd = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn photography_config.wsgi:application --bind 0.0.0.0:${PORT:-8000}"