[build]
builder = "nixpacks"
buildCommand = "python -m pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn photography_config.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
type = "web"