# Generated by Django 4.2.7 on 2025-10-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_remove_photo_thumbnail_alter_photo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="is_hero",
            field=models.BooleanField(
                default=False, help_text="Display in hero carousel"
            ),
        ),
    ]
