# Generated by Django 4.2.7 on 2025-10-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_photo_is_hero"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="selected_photos",
            field=models.ManyToManyField(
                blank=True,
                help_text="Photos selected by client for final delivery",
                related_name="selected_in_galleries",
                to="portfolio.photo",
            ),
        ),
    ]
