# Generated by Django 4.2.7 on 2025-10-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_gallery_selected_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="is_about_photo",
            field=models.BooleanField(
                default=False, help_text="Use as Daniel's photo in About section"
            ),
        ),
    ]
